pipeline:
  build:
    image: themast/docker-wp-theme-build:latest
    commands:
    - npm install -g --unsafe yarn bower-cli
    - yarn install
    - gulp package
    - git config remote.origin.url 'https://${GITHUB_TOKEN}@github.com/the-mast/presson-theme.git'
    - git tag v0.0.1-${DRONE_COMMIT_SHA}
    - git push origin v0.0.1-${DRONE_COMMIT_SHA}

  deploy:
    image: drillster/drone-rsync:latest
    hosts: [ '${REMOTE_IP_ADDRESS}' ]
    key: ${REMOTE_RSA_KEY}
    source: ./packaged/*
    target: /var/www/html/wp-content/themes/presson-theme
    delete: true
    script:
          - cd /var/www/html/wp-content/themes/presson-theme
          - find . -mindepth 1 ! -name "*.zip" -delete
          - unzip "`ls *.zip | tail -1`"
          - rm -f *.zip

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: the-mast-status
    username: drone-ci
    when:
      status: [ success, failure ]
    icon_url: http://plugins.drone.io/logo.svg
    template: |
      {{ repo.name }} finished build {{ build.number }}
        with a status of {{ build.status }}
