pipeline:
  build:
    image: themast/docker-wp-theme-build:latest
    commands:
      - npm install -g gulp-cli bower && npm install --unsafe-perm
      - git clone --depth=1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
      - npm install
      - npm install -g gulp-cli
      - cd wpcs && composer install
      - gulp phpcs
      - gulp phpcbf
      - gulp build && gulp package
      - cd ..
      - git config remote.origin.url 'https://${GITHUB_TOKEN}@github.com/the-mast/webstarterkit-spike.git'
      - git tag v0.0.1-${DRONE_COMMIT_SHA}
      - git push origin v0.0.1-${DRONE_COMMIT_SHA}

  deploy:
    image: drillster/drone-rsync:latest
    hosts: [ '${REMOTE_IP_ADDRESS}' ]
    key: ${REMOTE_RSA_KEY}
    source: ./packaged/*
    target: /var/www/html/wp-content/themes/mast-theme
    delete: true
    script:
          - cd /var/www/html/wp-content/themes/mast-theme
          - unzip -of *.zip
          - rm *.zip

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: the-mast-status
    username: drone-ci
    when:
      status: [ success, failure ]
    icon_url: http://plugins.drone.io/logo.svg
    template: |
      {{ repo.name }} finished build {{ build.number }}
        with a status of {{ build.status }}
